spring:
  profiles:
    active: dev
  application:
    name: sweet-shop-user
  datasource:
    driver-class-name: ${sweet.datasource.driver-class-name}
    url: ${sweet.datasource.url}
    username: ${sweet.datasource.username}
    password: ${sweet.datasource.password}
  data:
    redis:
      host: ${sweet.redis.host}
      database: ${sweet.redis.database}
  cloud:
    nacos:
      server-addr: ${sweet.cloud.nacos.server-addr}
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sweet.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sweet:
  alipay:
    app-id: ${sweet.alipay.app-id}
    private-key: ${sweet.alipay.private-key}
    alipay-public-key: ${sweet.alipay.alipay-public-key}
    gateway-url: ${sweet.alipay.gateway-url}

  jwt:
    admin-secret-key: yyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzbbbbbbbbbbbbbbbbbbbb
    admin-ttl: 18000000
    admin-token-name: token

    rider-secret-key: yyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzbbbbbbbbbbbbbbbbbbbb
    rider-ttl: 18000000
    rider-token-name: riderToken

    user-secret-key: yyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzbbbbbbbbbbbbbbbbbbbb
    user-ttl: 18000000
    user-token-name: authentication