sweet:
  auth:
    excludePaths:
      - /items/user/dish/search/**
      - /user/login
      - /admin/employee/login
      - /rider/login
      - /items/user/dish/list
      - /items/user/setmeal/list
      - /items/user/category/list
  jwt:
    admin-secret-key: yyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzbbbbbbbbbbbbbbbbbbbb
    admin-ttl: 18000000
    admin-token-name: token

    rider-secret-key: yyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzbbbbbbbbbbbbbbbbbbbb
    rider-ttl: 18000000
    rider-token-name: riderToken

    user-secret-key: yyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzbbbbbbbbbbbbbbbbbbbb
    user-ttl: 18000000
    user-token-name: authentication